//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Familia_Call_Centar.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testnaEntities : DbContext
    {
        public testnaEntities()
            : base("name=testnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<jelo> jelo { get; set; }
        public virtual DbSet<narudzba> narudzba { get; set; }
        public virtual DbSet<narudzba_item> narudzba_item { get; set; }
        public virtual DbSet<vozac> vozac { get; set; }
        public virtual DbSet<vozilo> vozilo { get; set; }
        public virtual DbSet<voznja> voznja { get; set; }
        public virtual DbSet<checkpoint> checkpoint { get; set; }
        public virtual DbSet<lokacija> lokacija { get; set; }
    }
}
