//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Familia_Call_Centar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class narudzba_item
    {
        public narudzba_item(int kvantitet, Double ukupna_cijena, int jeloID, int narudzbaID)
        {
            this.kvantitet = kvantitet;
            this.ukupna_cijena = ukupna_cijena;
            this.jeloID = jeloID;
            this.narudzbaID = narudzbaID;
        }

        public int narudzba_itemID { get; set; }
        public int kvantitet { get; set; }
        public Nullable<double> ukupna_cijena { get; set; }
        public int jeloID { get; set; }
        public int narudzbaID { get; set; }
    
        public virtual jelo jelo { get; set; }
        public virtual narudzba narudzba { get; set; }
    }
}
