//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Familia_Call_Centar.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class vozac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vozac(string ime, string prezime, int id, string pass)
        {
            this.voznja = new ObservableCollection<voznja>();
            this.ime = ime;
            this.prezime = prezime;
            this.vozacID = id;
            this.passsword = pass;
        }
    
        public int vozacID { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string passsword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<voznja> voznja { get; set; }
    }
}
